argocd staging:
  variables:
    S_TG_BOT_TOKEN: 7343501207:AAFRXuFq8xXwP6FiIyTIESuuVwpKj10ts_w
include:
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/global/stages&.yml
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/jobs/build/kaniko&.yml
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/jobs/deploy/argocd-staging&.yml
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/jobs/utils/with-submodules&.yml
  - remote: https://devops-pipeline-manager-production.trendsurfers.ru/manifest.yml?sources=/ci/workflow/review-on-mr&.yml
variables:
  DEPLOY_FROM: .k8s
  MAINTAINERS: vapvapapvpva@yandex.ru
  POSTGRES_ENABLED: 'true'

  HTTP_ENABLED: "true"
  HTTP_SUBDOMAIN_ON: ".trendsurfers.ru"
  HTTP_DOMAIN: "tma-jetlag-promo-backend.trendsurfers.ru"